'use strict';

const { ethers } = require('ethers');
const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

dotenv.config({ path: path.join(__dirname, '..', '..', 'env') });

const RPC_URL = process.env.AMOY_RPC_URL;
const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS;

if (!CONTRACT_ADDRESS) {
  console.error('⚠️  blockchainService: CONTRACT_ADDRESS not set in env file!');
}

// Load ABI from the frontend artifacts (PharmaSupplyChain.json is generated by Hardhat)
let contractABI = [];
try {
  // Try the compiled artifact first
  const artifactPath = path.join(__dirname, '..', '..', 'frontend', 'src', 'contracts', 'PharmaSupplyChain.json');
  const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
  contractABI = artifact.abi;
  console.log('blockchainService: ABI loaded from PharmaSupplyChain.json');
} catch (_) {
  // Fallback: minimal inline ABI matching PharmaSupplyChainCompatible
  console.warn('blockchainService: Could not load ABI from file, using fallback ABI');
  contractABI = [
    'function mintBatch(string tokenURI, string batchID, string metadataHash)',
    'function transferBatch(uint256 tokenId, address newOwner)',
    'function transferParentAndChildren(uint256 parentId, address newOwner)',
    'function getBatchDetails(uint256 tokenId) view returns (tuple(uint256 tokenId, address currentOwner, uint8 currentRole, string batchID, string metadataHash, string metadataURI, string qrCodeURI, uint256 timestamp, address manufacturer))',
    'function getTransferHistory(uint256 tokenId) view returns (tuple(address from, address to, uint256 timestamp, uint8 fromRole, uint8 toRole)[])',
    'function getRole(address user) view returns (uint8)',
    'function tokenCounter() view returns (uint256)',
    'function ownerOf(uint256 tokenId) view returns (address)',
    'function isManufacturer(address _manufacturer) view returns (bool)',
    'function isCounterfeit(uint256 tokenId) view returns (bool)',
    'function scannedByRole(uint256 tokenId, uint8 role) view returns (bool)',
    'function recordScan(uint256 tokenId)',
    'function getChildBatches(uint256 parentId) view returns (uint256[])',
    'function getParentBatch(uint256 childId) view returns (uint256)',
    'event BatchMinted(uint256 indexed tokenId, address indexed manufacturer, string batchID)',
    'event OwnershipTransferred(uint256 indexed tokenId, address indexed from, address indexed to, uint8 toRole)',
  ];
}

// Role enum matching the contract
const ROLE_NAMES = {
  0: 'None',
  1: 'Manufacturer',
  2: 'Distributor',
  3: 'Retailer',
  4: 'Pharmacy',
};

// ══════════════════════════════════════════════════════════════
//  HELPER METHODS
// ══════════════════════════════════════════════════════════════

/**
 * Returns a read-only instance of the contract.
 */
function getContract() {
  const provider = new ethers.JsonRpcProvider(RPC_URL);
  return new ethers.Contract(CONTRACT_ADDRESS, contractABI, provider);
}

/**
 * Connects a specific private key to the contract for writing.
 */
function getContractWithSigner(privateKey) {
  const provider = new ethers.JsonRpcProvider(RPC_URL);
  const wallet = new ethers.Wallet(privateKey, provider);
  return new ethers.Contract(CONTRACT_ADDRESS, contractABI, wallet);
}

// ══════════════════════════════════════════════════════════════
//  API METHODS — Fixed to use actual PharmaSupplyChainCompatible functions
// ══════════════════════════════════════════════════════════════

/**
 * createMedicineBatch: Mints a new batch NFT on-chain.
 * Calls mintBatch(tokenURI, batchID, metadataHash) — the actual contract function.
 *
 * @param {string} privateKey  - Manufacturer's private key
 * @param {string} batchID     - Human-readable batch identifier (e.g. BATCH-2026-08A)
 * @param {string} tokenURI    - Metadata URI (MongoDB ref or data URI)
 * @param {string} metadataHash - SHA-256 hash of batch metadata for integrity verification
 */
async function createMedicineBatch(privateKey, batchID, tokenURI, metadataHash = '') {
  const contract = getContractWithSigner(privateKey);
  const tx = await contract.mintBatch(tokenURI, batchID, metadataHash);
  const receipt = await tx.wait();

  // Find the BatchMinted event to get the new tokenId
  let tokenId = null;
  for (const log of receipt.logs) {
    try {
      const parsed = contract.interface.parseLog(log);
      if (parsed && parsed.name === 'BatchMinted') {
        tokenId = parsed.args[0].toString();
        break;
      }
    } catch (_) {}
  }

  return {
    success: true,
    txHash: tx.hash,
    batchId: tokenId,
    blockNumber: receipt.blockNumber,
  };
}

/**
 * updateBatchStage: Transfers a batch to the next stakeholder using the unified
 * transferBatch(tokenId, newOwner) function on the contract.
 *
 * @param {string} privateKey      - Sender's private key
 * @param {number} tokenId         - On-chain token ID (NOT the batchID string)
 * @param {string} targetAddress   - Recipient's Ethereum address
 */
async function updateBatchStage(privateKey, tokenId, targetAddress) {
  const contract = getContractWithSigner(privateKey);

  // Use transferBatch — the single unified transfer function in the contract
  const tx = await contract.transferBatch(tokenId, targetAddress);
  const receipt = await tx.wait();

  return {
    success: true,
    txHash: tx.hash,
    blockNumber: receipt.blockNumber,
  };
}

/**
 * getBatchProvenance: Returns the full lifecycle timeline array for a batch.
 * Maps on-chain TransferRecord struct fields (from, to, timestamp, fromRole, toRole).
 *
 * @param {number} tokenId - On-chain token ID
 */
async function getBatchProvenance(tokenId) {
  const contract = getContract();
  const history = await contract.getTransferHistory(tokenId);

  return history.map(record => ({
    from: record.from,
    to: record.to,
    fromRole: Number(record.fromRole),
    fromRoleName: ROLE_NAMES[Number(record.fromRole)] || 'Unknown',
    toRole: Number(record.toRole),
    toRoleName: ROLE_NAMES[Number(record.toRole)] || 'Unknown',
    timestamp: Number(record.timestamp),
    // Note: stage and digitalSignature are not in the contract struct —
    // they must be fetched from MongoDB's transfer history
  }));
}

/**
 * verifyBatchAuthenticity: Reads batch details and checks authenticity off-chain.
 * Uses read-only calls to avoid the role restriction on verifyBatch().
 *
 * @param {number} tokenId - On-chain token ID
 */
async function verifyBatchAuthenticity(tokenId) {
  const contract = getContract();

  try {
    // Get batch details using read-only calls (no role restriction)
    const [batchDetails, owner, isCounterfeitFlag] = await Promise.all([
      contract.getBatchDetails(tokenId),
      contract.ownerOf(tokenId).catch(() => null),
      contract.isCounterfeit(tokenId).catch(() => false),
    ]);

    const currentOwnerMatches = owner &&
      owner.toLowerCase() === batchDetails.currentOwner?.toLowerCase();

    return {
      isAuthentic: currentOwnerMatches && !isCounterfeitFlag,
      isCounterfeit: isCounterfeitFlag,
      currentOwner: batchDetails.currentOwner,
      currentRole: Number(batchDetails.currentRole),
      currentRoleName: ROLE_NAMES[Number(batchDetails.currentRole)] || 'Unknown',
      batchID: batchDetails.batchID,
      manufacturer: batchDetails.manufacturer,
    };
  } catch (error) {
    return {
      isAuthentic: false,
      error: error.message,
    };
  }
}

/**
 * getBatchDetails: Returns full batch details for a given token ID.
 */
async function getBatchDetails(tokenId) {
  const contract = getContract();
  const details = await contract.getBatchDetails(tokenId);
  return {
    tokenId: Number(details.tokenId),
    currentOwner: details.currentOwner,
    currentRole: Number(details.currentRole),
    currentRoleName: ROLE_NAMES[Number(details.currentRole)] || 'Unknown',
    batchID: details.batchID,
    metadataHash: details.metadataHash,
    metadataURI: details.metadataURI,
    timestamp: Number(details.timestamp),
    manufacturer: details.manufacturer,
  };
}

module.exports = {
  createMedicineBatch,
  updateBatchStage,
  getBatchProvenance,
  verifyBatchAuthenticity,
  getBatchDetails,
  getContract,
  getContractWithSigner,
  ROLE_NAMES,
};
